server:
  port: 8092

spring:
  application:
    name: attendance-store
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb1

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
  serviceUrl:
    defaultZone: 'http://localhost:8761/eureka/'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: '${spring.application.name}'

logging:
  level:
    com:
      training: DEBUG
  pattern:
    level: '%5p [${spring.application.name},%X{trace_id},%X{span_id}]'

